variable "resource_group_name" {}
variable "resource_group_location" {}
variable "key_vault_name" {}
variable "virtual_network_name" {}
variable "frontend_subnet_name" {}
variable "backend_subnet_name" {}
variable "frontend_pip_name" {}
variable "backend_pip_name" {}
variable "frontend_vm_name" {}
variable "backend_vm_name" {}
variable "frontend_nic_name" {}
variable "backend_nic_name" {}
variable "frontend_ip_name" {}
variable "backend_ip_name" {}
variable "sql_server_name" {}
variable "sql_database_name" {}
variable "vm_username_secret_name" {}
variable "vm_password_secret_name" {}